apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      annotations:
        resource.opentelemetry.io/frontend: "true"
        instrumentation.opentelemetry.io/inject-python: "mw-agent-ns/mw-autoinstrumentation"
      labels:
        app: python-service
    spec:
      containers:
        - name: python-service
          image: tejaskokje/python-service
          ports:
            - containerPort: 8080

